"""
Q-Learning Maze Solver

A tabular reinforcement learning implementation that learns to solve mazes
using Q-learning with epsilon-greedy exploration.

Architecture:
- MazeEnvironment: Manages maze state and validates moves
- QLearningAgent: Implements Q-learning algorithm with Q-table
- Training loop: Runs episodes and communicates with JavaScript

Communication Pattern:
- Python sends data-only to JavaScript via window callbacks
- JavaScript handles all UI rendering
"""

import asyncio
from js import window, Object, console
from pyodide.ffi import to_js
from lib.pyscript_manager import PyScriptManager


# Action constants (matches JavaScript Actions enum)
class Actions:
    UP = 'UP'
    DOWN = 'DOWN'
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'

    @classmethod
    def all(cls):
        return [cls.UP, cls.DOWN, cls.LEFT, cls.RIGHT]


class MazeEnvironment:
    """
    Maze environment that manages state and validates moves.

    The maze grid comes from JavaScript (generated by recursive backtracker).
    Python receives the grid structure and manages agent movement.
    """

    def __init__(self, maze_data):
        """
        Initialize environment from JavaScript maze data.

        Args:
            maze_data: JS object with { grid, rows, cols, startPos, endPos }
        """
        # Convert JS objects to Python
        self.rows = maze_data.rows
        self.cols = maze_data.cols
        self.start_pos = {'row': maze_data.startPos.row, 'col': maze_data.startPos.col}
        self.end_pos = {'row': maze_data.endPos.row, 'col': maze_data.endPos.col}

        # Convert grid (preserve wall structure)
        self.grid = []
        for r in range(self.rows):
            row = []
            for c in range(self.cols):
                cell = maze_data.grid[r][c]
                walls = cell.walls
                row.append({
                    'walls': {
                        'top': walls.top,
                        'right': walls.right,
                        'bottom': walls.bottom,
                        'left': walls.left
                    }
                })
            self.grid.append(row)

        console.log(f"[Python] MazeEnvironment initialized: {self.rows}x{self.cols}")

    def reset(self):
        """Reset environment to start position."""
        return dict(self.start_pos)

    def can_move(self, row, col, action):
        """
        Check if move is valid (no wall blocking).

        Args:
            row, col: Current position
            action: Action to take (UP/DOWN/LEFT/RIGHT)

        Returns:
            bool: True if move is valid
        """
        if row < 0 or row >= self.rows or col < 0 or col >= self.cols:
            return False

        direction_map = {
            Actions.UP: 'top',
            Actions.DOWN: 'bottom',
            Actions.LEFT: 'left',
            Actions.RIGHT: 'right'
        }

        wall_dir = direction_map.get(action)
        if wall_dir is None:
            return False

        return not self.grid[row][col]['walls'][wall_dir]

    def step(self, state, action):
        """
        Execute action and return next state, reward, done.

        Args:
            state: Current state dict {row, col}
            action: Action to take

        Returns:
            tuple: (next_state, reward, done)
        """
        row, col = state['row'], state['col']

        # Try to move
        if not self.can_move(row, col, action):
            # Hit wall - stay in place
            next_state = dict(state)
            reward = -1  # Step penalty
            done = False
            return next_state, reward, done

        # Calculate next position
        next_row, next_col = row, col
        if action == Actions.UP:
            next_row -= 1
        elif action == Actions.DOWN:
            next_row += 1
        elif action == Actions.LEFT:
            next_col -= 1
        elif action == Actions.RIGHT:
            next_col += 1

        next_state = {'row': next_row, 'col': next_col}

        # Check if reached goal
        if next_row == self.end_pos['row'] and next_col == self.end_pos['col']:
            reward = 100  # Goal reward
            done = True
        else:
            reward = -1  # Step penalty
            done = False

        return next_state, reward, done

    def is_goal(self, state):
        """Check if state is the goal."""
        return state['row'] == self.end_pos['row'] and state['col'] == self.end_pos['col']


class QLearningAgent:
    """
    Q-Learning agent with epsilon-greedy exploration.

    Maintains a Q-table mapping (state, action) pairs to Q-values.
    Uses the Bellman equation to update Q-values based on experience.
    """

    def __init__(self, alpha=0.1, gamma=0.95, epsilon=1.0, epsilon_decay=0.995, epsilon_min=0.01):
        """
        Initialize Q-learning agent.

        Args:
            alpha: Learning rate (0-1)
            gamma: Discount factor (0-1)
            epsilon: Initial exploration rate (0-1)
            epsilon_decay: Epsilon decay rate per episode
            epsilon_min: Minimum epsilon value
        """
        self.q_table = {}  # Q-table: "row,col:action" -> Q-value
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min

        self.episodes = 0
        self.total_steps = 0

        console.log(f"[Python] QLearningAgent initialized (α={alpha}, γ={gamma}, ε={epsilon})")

    def _state_key(self, state):
        """Convert state to string key."""
        return f"{state['row']},{state['col']}"

    def _q_key(self, state, action):
        """Convert state-action pair to Q-table key."""
        return f"{self._state_key(state)}:{action}"

    def get_q_value(self, state, action):
        """Get Q-value for state-action pair (default 0)."""
        key = self._q_key(state, action)
        return self.q_table.get(key, 0.0)

    def set_q_value(self, state, action, value):
        """Set Q-value for state-action pair."""
        key = self._q_key(state, action)
        self.q_table[key] = value

    def choose_action(self, state):
        """
        Choose action using epsilon-greedy strategy.

        Args:
            state: Current state

        Returns:
            str: Action to take
        """
        import random

        if random.random() < self.epsilon:
            # Explore: random action
            return random.choice(Actions.all())
        else:
            # Exploit: best known action
            return self.get_best_action(state)

    def get_best_action(self, state):
        """Get action with highest Q-value for state."""
        actions = Actions.all()
        best_action = actions[0]
        best_value = self.get_q_value(state, best_action)

        for action in actions[1:]:
            value = self.get_q_value(state, action)
            if value > best_value:
                best_value = value
                best_action = action

        return best_action

    def update_q_value(self, state, action, reward, next_state):
        """
        Update Q-value using Bellman equation.

        Q(s,a) = Q(s,a) + α[r + γ·max(Q(s',a')) - Q(s,a)]

        Args:
            state: Current state
            action: Action taken
            reward: Reward received
            next_state: Resulting state
        """
        current_q = self.get_q_value(state, action)

        # Find max Q-value for next state
        max_next_q = max(self.get_q_value(next_state, a) for a in Actions.all())

        # Bellman equation
        new_q = current_q + self.alpha * (reward + self.gamma * max_next_q - current_q)

        self.set_q_value(state, action, new_q)

    def decay_epsilon(self):
        """Decay exploration rate."""
        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)

    def get_q_values_for_visualization(self):
        """
        Get Q-values organized by state for JavaScript visualization.

        Returns:
            dict: { "row,col": { "UP": q_value, "DOWN": q_value, ... } }
        """
        q_values = {}

        for key, value in self.q_table.items():
            # Split "row,col:action" into state_key and action
            parts = key.split(':')
            if len(parts) == 2:
                state_key, action = parts
                if state_key not in q_values:
                    q_values[state_key] = {}
                q_values[state_key][action] = value

        return q_values


class MazeRLTrainer:
    """
    Training orchestrator that runs Q-learning episodes and
    communicates progress to JavaScript.
    """

    def __init__(self):
        self.env = None
        self.agent = None
        self.is_training = False
        self.is_paused = False
        self.is_demo = False  # Demo mode flag

        # Statistics
        self.current_episode = 0
        self.success_count = 0
        self.episode_rewards = []

        console.log("[Python] MazeRLTrainer initialized")

    def set_maze(self, maze_data):
        """Initialize environment with new maze."""
        self.env = MazeEnvironment(maze_data)
        self.agent = QLearningAgent()

        # Reset statistics
        self.current_episode = 0
        self.success_count = 0
        self.episode_rewards = []

        console.log(f"[Python] Maze set, ready to train")

    async def run_episode(self, max_steps=1000, visualize_every=5):
        """
        Run a single training episode.

        Args:
            max_steps: Maximum steps per episode
            visualize_every: Update visualization every N steps

        Returns:
            dict: Episode statistics
        """
        if not self.env or not self.agent:
            console.error("[Python] No environment set!")
            return None

        state = self.env.reset()
        episode_reward = 0
        steps = 0
        reached_goal = False

        while steps < max_steps:
            # Choose action
            action = self.agent.choose_action(state)

            # Execute action
            next_state, reward, done = self.env.step(state, action)

            # Update Q-value
            self.agent.update_q_value(state, action, reward, next_state)

            # Update state and stats
            state = next_state
            episode_reward += reward
            steps += 1

            # Visualize agent movement (throttled)
            if steps % visualize_every == 0 and hasattr(window, 'mazeRLCallbacks'):
                if hasattr(window.mazeRLCallbacks, 'onAgentMove'):
                    window.mazeRLCallbacks.onAgentMove(to_js({
                        'position': {'row': state['row'], 'col': state['col']},
                        'action': action,
                        'reward': episode_reward,
                        'steps': steps
                    }, dict_converter=Object.fromEntries))
                    # Small delay to allow visualization
                    await asyncio.sleep(0.01)

            if done:
                reached_goal = True
                self.success_count += 1
                break

        # Episode complete
        self.current_episode += 1
        self.agent.episodes += 1
        self.agent.decay_epsilon()
        self.episode_rewards.append(episode_reward)

        # Send metrics update to JavaScript
        if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onMetricsUpdate'):
            success_rate = (self.success_count / self.current_episode * 100) if self.current_episode > 0 else 0

            window.mazeRLCallbacks.onMetricsUpdate(to_js({
                'episode': self.current_episode,
                'steps': steps,
                'reward': episode_reward,
                'epsilon': self.agent.epsilon,
                'successRate': f"{success_rate:.1f}",
                'qValues': to_js(self.agent.get_q_values_for_visualization())
            }))

        # Episode end callback
        if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onEpisodeEnd'):
            window.mazeRLCallbacks.onEpisodeEnd(to_js({
                'episode': self.current_episode,
                'steps': steps,
                'reward': episode_reward,
                'reachedGoal': reached_goal
            }))

        return {
            'episode': self.current_episode,
            'steps': steps,
            'reward': episode_reward,
            'reached_goal': reached_goal
        }

    async def train(self, num_episodes=None):
        """
        Run training loop.

        Args:
            num_episodes: Number of episodes to train (None = infinite)
        """
        self.is_training = True
        self.is_paused = False

        console.log(f"[Python] Training started")

        episode_count = 0
        while self.is_training:
            if self.is_paused:
                await asyncio.sleep(0.1)
                continue

            # Run episode
            await self.run_episode()

            # Check if we should stop
            episode_count += 1
            if num_episodes is not None and episode_count >= num_episodes:
                break

            # Small delay between episodes
            await asyncio.sleep(0.05)

        console.log(f"[Python] Training stopped after {episode_count} episodes")

    def pause(self):
        """Pause training."""
        self.is_paused = True
        console.log("[Python] Training paused")

    def resume(self):
        """Resume training."""
        self.is_paused = False
        console.log("[Python] Training resumed")

    def stop(self):
        """Stop training."""
        self.is_training = False
        self.is_paused = False
        console.log("[Python] Training stopped")

    def reset(self):
        """Reset training statistics and Q-table."""
        if self.agent:
            self.agent = QLearningAgent()

        self.current_episode = 0
        self.success_count = 0
        self.episode_rewards = []

        console.log("[Python] Training reset")

    async def run_demo(self, max_steps=1000):
        """
        Run demonstration using learned policy (epsilon = 0).
        Shows what the agent has learned without exploration or Q-value updates.

        Args:
            max_steps: Maximum steps per demo

        Returns:
            dict: Demo statistics
        """
        if not self.env or not self.agent:
            console.error("[Python] No environment set!")
            return None

        console.log("[Python] Starting demo mode (pure exploitation, no learning)")

        # Save current epsilon and set to 0 for pure exploitation
        original_epsilon = self.agent.epsilon
        self.agent.epsilon = 0.0

        self.is_demo = True

        state = self.env.reset()

        # Reset agent to start position in UI
        if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onAgentMove'):
            window.mazeRLCallbacks.onAgentMove(to_js({
                'position': {'row': state['row'], 'col': state['col']},
                'action': 'NONE',
                'reward': 0,
                'steps': 0
            }, dict_converter=Object.fromEntries))
            await asyncio.sleep(0.5)  # Brief pause to show reset

        # Notify UI of demo start
        if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onMetricsUpdate'):
            window.mazeRLCallbacks.onMetricsUpdate(to_js({
                'episode': self.current_episode,
                'steps': 0,
                'reward': 0,
                'epsilon': 0.0,
                'successRate': f"{(self.success_count / max(self.current_episode, 1) * 100):.1f}",
                'qValues': to_js(self.agent.get_q_values_for_visualization())
            }))
        episode_reward = 0
        steps = 0
        reached_goal = False
        start_time = None

        # Track start time for elapsed calculation
        from js import Date
        start_time = Date.now()

        while steps < max_steps and self.is_demo:
            # Choose best action (no exploration)
            action = self.agent.get_best_action(state)

            # Execute action
            next_state, reward, done = self.env.step(state, action)

            # NO Q-value update during demo!

            # Update state and stats
            state = next_state
            episode_reward += reward
            steps += 1

            # Visualize every step during demo (slower, more visible)
            if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onAgentMove'):
                window.mazeRLCallbacks.onAgentMove(to_js({
                    'position': {'row': state['row'], 'col': state['col']},
                    'action': action,
                    'reward': episode_reward,
                    'steps': steps
                }, dict_converter=Object.fromEntries))
                # Slower delay for demo visibility (400ms per step)
                await asyncio.sleep(0.4)

            if done:
                reached_goal = True
                break

        # Calculate elapsed time
        elapsed_ms = Date.now() - start_time
        elapsed_sec = elapsed_ms / 1000.0

        # Demo complete
        result_msg = "✅ Goal reached!" if reached_goal else "❌ Failed to reach goal"
        console.log(f"[Python] Demo complete: {result_msg} Steps: {steps}, Time: {elapsed_sec:.2f}s")

        # Restore original epsilon
        self.agent.epsilon = original_epsilon
        self.is_demo = False

        # Notify UI of demo completion with elapsed time
        if hasattr(window, 'mazeRLCallbacks'):
            if hasattr(window.mazeRLCallbacks, 'onDemoComplete'):
                window.mazeRLCallbacks.onDemoComplete(to_js({
                    'steps': steps,
                    'reward': episode_reward,
                    'reachedGoal': reached_goal,
                    'elapsedTime': elapsed_sec
                }))

            if hasattr(window.mazeRLCallbacks, 'onEpisodeEnd'):
                window.mazeRLCallbacks.onEpisodeEnd(to_js({
                    'episode': self.current_episode,
                    'steps': steps,
                    'reward': episode_reward,
                    'reachedGoal': reached_goal
                }))

        return {
            'steps': steps,
            'reward': episode_reward,
            'reached_goal': reached_goal
        }


# Global trainer instance
_trainer = MazeRLTrainer()


# Exposed functions for JavaScript to call
def set_maze(maze_data):
    """Set maze for training (called from JavaScript)."""
    _trainer.set_maze(maze_data)


def start_training():
    """Start training loop (called from JavaScript)."""
    console.log("[Python] start_training() called")

    # Run training in background
    import asyncio
    asyncio.ensure_future(_trainer.train())


def pause_training():
    """Pause training (called from JavaScript)."""
    _trainer.pause()


def resume_training():
    """Resume training (called from JavaScript)."""
    _trainer.resume()


def stop_training():
    """Stop training (called from JavaScript)."""
    _trainer.stop()


def reset_training():
    """Reset training (called from JavaScript)."""
    _trainer.reset()

    # Send reset metrics to JavaScript
    if hasattr(window, 'mazeRLCallbacks') and hasattr(window.mazeRLCallbacks, 'onMetricsUpdate'):
        window.mazeRLCallbacks.onMetricsUpdate(to_js({
            'episode': 0,
            'steps': 0,
            'reward': 0,
            'epsilon': 1.0,
            'successRate': '0.0',
            'qValues': to_js({})
        }))


def run_demo():
    """Run demo with learned policy (called from JavaScript)."""
    console.log("[Python] run_demo() called")

    # Stop any ongoing training or previous demo
    _trainer.stop()
    _trainer.is_demo = False  # Stop any running demo

    # Run demo in background
    import asyncio
    asyncio.ensure_future(_trainer.run_demo())


# Initialize PyScriptManager and signal ready
console.log("[Python] Q-Learning module loading...")

manager = PyScriptManager("q_learning")
manager.signal_ready(extra_exports={
    'setMaze': set_maze,
    'startTraining': start_training,
    'pauseTraining': pause_training,
    'resumeTraining': resume_training,
    'stopTraining': stop_training,
    'resetTraining': reset_training,
    'runDemo': run_demo
})

console.log("[Python] Q-Learning module ready! ✅")
